### PR TITLE
Upgrade to leptos v0.5.0-rc2

### PR DESCRIPTION
**Pull request by DonAlonzo**
Reference commit 2c18fc66f0997be0064fca2e42013274b78753bb used to upgrade.

### CODE REVIEW

**Comment by nicoburniske** [comment]
Hey thanks a lot for doing this. I can't look at it in depth until tomorrow, and then hopefully release a 0.5 compatible version this weekend

**Comment by srid** [comment]
Leptos 0.5 [got released](https://github.com/leptos-rs/leptos/releases/tag/v0.5.0)!

It'd be great to have this merged and released as a crate, we use this library in https://github.com/juspay/nix-browser :-)

**Review by nicoburniske — APPROVED** [review]
Looks good. Some of the examples are broken, but I'll merge this and then fix them myself. Thanks again

**Comment by srid** [comment]
Thanks for the release. Trying it out, I see hydration errors: https://github.com/juspay/nix-browser/pull/78#issuecomment-1743182253

I'll try to figure out a minimal repro ...

**Pull request merged**
